language: cpp
compiler:
    - gcc
before_install:
    - sudo apt-get -y update
    - sudo apt-get install -y cython libboost-all-dev libboost-random-dev python python-setuptools
    - sudo apt-get install -y python-numpy python-scipy

install:
    - sudo python setup.py install
